### ISSUE TITLE
Standoff holes in brd?

### ISSUE THREAD

**Issue by ghost** [sparkfun/MIDI_Shield#11]
Should we include them for use in an enclosure?

**Comment by ghost** [comment]
I use the terms "standoff" and "mounting" here interchangeably.

**Comment by Jacquot-SFE** [comment]
I skipped them on purpose.

Mechanically, this thing doesn't really provide for easy mounting in an
enclosure.  The connectors are tall, much taller than the adjacent
pushbuttons.  If it's mounted on a Uno or Redboard, the shield is
considerably shorter than the host board - the USB connector sticks out
about 3/4" past the MIDI plugs.

I suppose we could include the one hole near the SCL pin, but it's mostly
useless because it's too close to the header.

**Comment by ghost** [comment]
Your call.
