### ISSUE TITLE
using soft serial on pins 8 and 9

### ISSUE THREAD

**Issue by 1mpar** [sparkfun/MIDI_Shield#13]
hi, I'm using this code - https://github.com/sparkfun/MIDI_Shield/blob/master/Firmware/MIDI-sniffer/MIDI-sniffer.ino
but I get no messages on the serial monitor. I think this code is for the new version of the shield, but is there a way to use soft serial on pins 8 and 9 on this version (sparkfun DEV 09595)?

**Comment by Jacquot-SFE** [comment]
If you're comfortable reworking the board a little bit, this is doable.

You can cut the TX and RX lines, and add jumpers to run them to pins 8 and 9.  I'd cut the RX line near the "G" in PROG, so the 220-Ohm resistor is still tied to the optocoupler, before it reaches the RUN/PROG switch.  You can cut the TX line anywhere between the shield pin and the 220-Ohm resistor, since there's no interceding circuitry.

**Comment by bboyho** [comment]
Hi,

It looks like Byron answered your question. The code is written for the latest MIDI Shield. However, as Byron stated above, you can reroute the pins on an ATmega328P-based Arduino to software serial and view the data on an Arduino Serial Monitor. Just make sure to select the correct baud rate since the output is 19200 baud.
