### ISSUE TITLE
Question: how to make an arpeggio?

### ISSUE THREAD

**Issue by billyjoker** [sparkfun/MIDI_Shield#14]
Hi, i have this shield and i would like to write some arpeggios, but i do not know how to handle it. Thanks!!

**Comment by Jacquot-SFE** [comment]
Howdy Billy,

I assume you want to build something like an arpeggiator on a keyboard, where you hold some notes, and the device will cycle through them?  If not, please add some detail about what you're trying to achieve.

I notice you found wbajzek's arpeggiator.

There's also the Mutable Instrument's [MIDIPal](https://github.com/pichenettes/midipal), which is a MIDI toolkit that includes an arpeggiator.

Finally, I put an arpeggiator in my [Werkstatt CV converter](https://learn.sparkfun.com/tutorials/midi-shield-hookup-guide/example-2-midi-to-control-voltage) project, but it outputs control voltage, not MIDI messages.  You could probably amend it to send MIDI instead.


-BGJ

**Comment by billyjoker** [comment]
Hi @Jacquot-SFE !!

Yes, i'd like to trigger some arpeggiated notes when i hold on a note in my midi keyboard. You are right, i've tried the  wbajzek's arpeggiator, but the performance is not very well...

My goal is to have stored a kit of arpeggios, select one of them, and trigger it with my midi keyboard.

I've just take a look at the Mutable Instrument's MIDIPal, can i load it to my Arduino? As i saw, it is written with Python....

I'm taking a look also to your Werkstatt CV converter, is this the [code](https://github.com/sparkfun/MIDI_Shield/blob/V_1.5/Firmware/MIDI-CV/MIDI-CV.ino) ?

Thanks again!!!

**Comment by Jacquot-SFE** [comment]
A couple of thoughts on this.

First, I'm not sure you're describing that a traditional arpeggiator does.  An old-school arpeggiator takes a handful of held keys, and hops between them based on some rule (up, down, up&down, random, etc).  You might check for videos of the old Roland SH101 arpeggiator in action.  It's got a pretty good one.

I take it you're looking for something that will start playing a predefined group of notes based on a single key press?  I'm not sure what it would be called, maybe an interactive phrase sequencer?

Either way, you should be able to make one using an Arduino + MIDI  shield...you just might not find one already written.

I haven't tried either wbajzek's or the MIDI pal, I just found them googling.  The MIDIPal was mentioned by a friend recently - it's based on an ATMEGA328P and standard MIDI hardware...which looks like a subset of an Uno & MIDI Shield.  The firmware is in [this subtree](https://github.com/pichenettes/midipal/tree/master/midipal), and the Python piece looks like a configuration app that runs alongside, since the MIDIpal itself only has a knob and small LCD.

Finally, that is my CV converter.  You'll also need the `notemap` files from that directory, and the fortyseven effects [MIDI library](http://github.com/FortySevenEffects/arduino_midi_library/).

**Comment by bboyho** [comment]
Hi,

It looks like Byron might have answered your questions. I'll be be closing this issue. If you have not already, it might be good to check out the SparkFun or Arduino.cc Forums to see if you can get some additional insight from others in the community on arpeggios if you are still in the process of building one. =) :

* [Arduino.cc Forums](https://forum.arduino.cc/)
* [SparkFun Forums](https://forum.sparkfun.com/)
